### PR TITLE
ORION-70: Add console to the editor.

### PR DESCRIPTION
**Pull request by markwongsk**
QE: Please test the following:
1. The "Run Tests" option only appears if the current file is a python file
2. The "Run Tests" option, when clicked, changes the option to "Cancel".
3. When the tests have finished running, the console pops up with the
   test output. Note that if the console is already open this doesn't
   have any effect. Also note that if the tests take forever, the
   console doesn't pop up until "Cancel" is clicked.
4. The console can be opened and closed as usual.
5. Refreshing the page persists console opened/closed state but does not
   persist console logs.
6. The "Clear" option clears the console when clicked.
7. Any misc edge cases.

CRR: vchu, mwlodarczyk

### CODE REVIEW

**Comment by markwongsk** [comment]
@vchu123 @w10d

**Comment by markwongsk** [comment]
Michał please assign to Victor after you give your +1, Victor, you can probably start testing this.

**Comment by vchu123** [comment]
P2
-Add "Console" name or something else to fill weird whitespace
-Run Tests - add highlighting?
-make highlighting of "run tests" like the highlighting of the arrow (highlight around background, not individual letters - it really should just feel more like a button >.<)
-same as above for "Clear"
-Warning that test file isn't saved (i messed this up like 3 times...)

P1?
-"Run Tests" action should spit some dialogue (running...etc and then delete) AND summon console by default (not just when it finishes running tests)
-arrow click weird - should make collapsible and collapse to header (next bullet)
-Add a header to each test run that includes the file name and a numerical counter (As a crappy example test.py Run 1 - check with docs/design for a better name)
-Auto-scroll when text outputs
-Need scroll bar always visible if scrollable (like in main code area)
-Clear button needs to be sticky at top (otherwise with long amounts of output, you have to scroll forever to find/click it

P0 - to be clear, do not lose sleep (just means critical before shipping this feature)
-Internal state not tracked - clicking the console to minimize or maximize causes weird interactions happen.  This is potentially hiding other behavior

PX - Disable shell with your commit

**Comment by markwongsk** [comment]
P2
-Add "Console" name or something else to fill weird whitespace
[Made the first log flushed top instead]
-Run Tests - add highlighting?
[Made it a button similar to the one for <File> <Edit> etc]
-make highlighting of "run tests" like the highlighting of the arrow (highlight around background, not individual letters - it really should just feel more like a button >.<)
[See above]
-same as above for "Clear"
[Didn't do this because Orion has no button on a white background, and their default styles weren't to my liking. You may file a bug if you want].
-Warning that test file isn't saved (i messed this up like 3 times...)
[Punting so file a bug]

P1?
-"Run Tests" action should spit some dialogue (running...etc and then delete) AND summon console by default (not just when it finishes running tests)
[Punting, file a bug]
-arrow click weird - should make collapsible and collapse to header (next bullet)
[Done]
-Add a header to each test run that includes the file name and a numerical counter (As a crappy example test.py Run 1 - check with docs/design for a better name)
[Punting, file a bug, will wait for user feedback]
-Auto-scroll when text outputs
[Done]
-Need scroll bar always visible if scrollable (like in main code area)
[Code area does not always have a visible scrollbar for me]
-Clear button needs to be sticky at top (otherwise with long amounts of output, you have to scroll forever to find/click it
[Done]

P0 - to be clear, do not lose sleep (just means critical before shipping this feature)
-Internal state not tracked - clicking the console to minimize or maximize causes weird interactions happen. This is potentially hiding other behavior
[Done]

**Comment by vchu123** [comment]
P2
-Add "Console" name or something else to fill weird whitespace
[Made the first log flushed top instead]
{Ok-I'll check out how it looks}
-Run Tests - add highlighting?
[Made it a button similar to the one for etc]
{Ok-I'll check out how it looks}
-make highlighting of "run tests" like the highlighting of the arrow (highlight around background, not individual letters - it really should just feel more like a button >.<)
[See above]
-same as above for "Clear"
[Didn't do this because Orion has no button on a white background, and their default styles weren't to my liking. You may file a bug if you want].
-Warning that test file isn't saved (i messed this up like 3 times...)
[Punting so file a bug]
{ok}

P1?
-"Run Tests" action should spit some dialogue (running...etc and then delete) AND summon console by default (not just when it finishes running tests)
[Punting, file a bug]
{ok}
-arrow click weird - should make collapsible and collapse to header (next bullet)
[Done]
-Add a header to each test run that includes the file name and a numerical counter (As a crappy example test.py Run 1 - check with docs/design for a better name)
[Punting, file a bug, will wait for user feedback]
-Auto-scroll when text outputs
[Done]
-Need scroll bar always visible if scrollable (like in main code area)
[Code area does not always have a visible scrollbar for me]
-Clear button needs to be sticky at top (otherwise with long amounts of output, you have to scroll forever to find/click it
[Done]

P0 - to be clear, do not lose sleep (just means critical before shipping this feature)
-Internal state not tracked - clicking the console to minimize or maximize causes weird interactions happen. This is potentially hiding other behavior
[Done]

Let me know when dev CR is done

**Comment by w10d** [comment]
ok, this looks fine now so I move to testing

**Comment by w10d** [comment]
My thoughts about UI ( @vchu123 please take a look at them):
1) Can we disable the links when the execution environment is disabled?
2) When execution takes some time and I switch my focus onto another file then I can't cancel the task explicitly (I can do this only by running another task).
3) In the same setting as (2): When I run a new task while the previous one is still working then the console immediately prints "Process terminated with the exit status 143". This refers to the previous task (that has been just canceled) but might be misleading. A possible fix is to print a message like "running..." (already occurred in Victor's P1).

**Comment by vchu123** [comment]
1) Can we disable the links when the execution environment is disabled? (testing now)
2) When execution takes some time and I switch my focus onto another file then I can't cancel the task explicitly (I can do this only by running another task).
this is a good point.  Maybe we should have a second cancel button?  @markwongsk ?
3) In the same setting as (2): When I run a new task while the previous one is still working then the console immediately prints "Process terminated with the exit status 143". This refers to the previous task (that has been just canceled) but might be misleading. A possible fix is to print a message like "running..." (already occurred in Victor's P1).
I think this will be resolved when we determine how to deal with multiple tasks at once (and of course front loading the message) so im less concerned about this for this week

**Comment by vchu123** [comment]
Last P1 to actually Fix
1.  We should warn user on navigating away from running task, warning them that it may result in orphaned process.  Since we are allowing users to run arbitrary code on the server, its not really feasible to catch ALL cases of problems.  That said, since we don't support running concurrent tests yet, let's just lock users to 1 test at a time and spit a warning dialogue and block users before they navigate away for now.

Others (not fixing for v1)
A.  Visibility of "run" isn't super usable as it appears instantly, without any animations so its tough to tell when things run, if they've run, and it also looks off when it first appears.  We don't have good ideas for fixing, and its definitely usable as is, so will file a ticket on designers to come up with a better long-term solution

B.  P3 - long text overlaps clear button - @markwongsk you can fix if its trivial, but don't spend too long on it.

C.  Disable link to run test when plugin execution environment disabled - this isn't actually a big deal as clicking the button tells you specifically that its disabled.  It COULD become an issue if our BD's want to hide this functionality, but we haven't had that request yet so we'll deal with it if they ask for it.  Will file a ticket but immediately "won't fix"

In response to Michal's "When execution takes some time and I switch my focus onto another file then I can't cancel the task explicitly (I can do this only by running another task)."
This will probably go in with concurrent task/test re-design.

**Comment by vchu123** [comment]
please update error message to 

"Warning: You are navigating away from a test that has not yet completed which may cause problems.  To cancel this test, simply start any other test."

other than that, +1 and go ahead and merge

**Pull request merged**
