### PR TITLE
ORION-96 fix for creating a new account

### PR DESCRIPTION
**Pull request by w10d**
Change-Id: Ia8bebfe05186c20973278888f3af07dec80b2a98

### CODE REVIEW

**Comment by w10d** [comment]
@markwongsk @vchu123

**Comment by vchu123** [comment]
looks reasonable to me

**Comment by w10d** [comment]
@markwongsk @vchu123 new version

**Comment by vchu123** [comment]
This _may_ have issues with context paths with multiple /'s but that will break many other places too, so we can deal with it if/when it becomes a use case

**Pull request merged**
