### PR TITLE
ORION-20 Add automatic import command

### PR DESCRIPTION
**Pull request by aaudiber**
This depends on https://github.com/palantir/orion.server/pull/10 for being able to access server configuration.

### CODE REVIEW

**Comment by aaudiber** [comment]
@mingyukim

**Comment by aaudiber** [comment]
good call, I'll add some

**Comment by aaudiber** [comment]
@w10d @mingyukim Are you all set on this change?

**Comment by w10d** [comment]
Ok for me now

**Comment by mingyukim** [comment]
This is adding a menu to auto-import, right? Can you make it configurable so that auto-import is well.. automatically done?

**Comment by aaudiber** [comment]
There's no way in Orion to automatically run a command. The context in which commands are executed involves a lot of state, and I've so far been unable to replicate it during editor setup :/

I'm going to take some time next week to investigate further, but for now this deals with 90% of the problem (having to figure out where the repo is), so I think it's worth merging.

**Comment by mingyukim** [comment]
+1 as long as you are following up on it.

**Pull request merged**
