### PR TITLE
ORION-72 git url can be specified for auto-import

### PR DESCRIPTION
**Pull request by w10d**
Change-Id: I0a37bdfeb85bb22f0318508300fa89f5b785f955

### CODE REVIEW

**Comment by w10d** [comment]
@vchu123

**Comment by w10d** [comment]
@markwongsk @vchu123

**Comment by w10d** [comment]
@markwongsk @vchu123

**Comment by vchu123** [comment]
Please make gerrit commit, and i'll check it out =)

**Pull request merged**
